  - alias: 'Close all blinds when the sun sets'
    trigger:
      platform: sun
      event: sunset
      offset: '+00:00:00'
    action:
      - service: cover.close_cover
        data:
          entity_id: group.covers
      - service: notify.notifiers
        data:
          title: Automation
          message: Deine Roll채den sind jetzt unten

  - alias: 'Get notified when garage door opens'
    trigger:
      platform: state
      entity_id: sensor.garage_door_status
      to: 'open'
    action:
      - service: notify.notifiers
        data:
          title: Warnung
          message: Deine Garage ist offen

  - alias: 'Get notified when garage door closes'
    trigger:
      platform: state
      entity_id: sensor.garage_door_status
      to: 'closed'
    action:
      - service: notify.notifiers
        data:
          title: Info
          message: Deine Garage ist jetzt geschlossen

  - alias: 'Next trash appointment notification'
    initial_state: True
    trigger:
      - platform: template
        value_template: "{% if states.sensor.trash_appointment_days.state | int < 1 %}true{% endif %}"
    action:
      service: notify.notifiers
      data_template:
        title: "M체llleerung!"
        message: "Die n채chste M체llleerung ist morgen ({{ states('sensor.trash_appointment') }}) !"

  - alias: 'Take pill reminder'
    initial_state: True
    trigger:
      - platform: template
        value_template: "{% if states.sensor.pill_reminder.state | int < 1 %}true{% endif %}"
    action:
      service: notify.pushbullet_kalo
      data_template:
        title: "Pille!"
        message: "Pille nehmen :-P."

  - alias: 'Take daily reminder'
    initial_state: True
    trigger:
      - platform: template
        value_template: "{% if states.sensor.daily_reminder.state | int < 1 %}true{% endif %}"
    action:
      service: notify.pushbullet_mwi
      data_template:
        title: "Tablette nehmen"
        message: "Tablette nehmen!"
