homeassistant:
  name: Daheim
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

default_config:

# Enables the frontend
frontend:

lovelace:

# Enables configuration UI
config:

zwave:
  usb_path: /dev/ttyACM0

http:
  ip_ban_enabled: True
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.202
    - 37.24.225.83

updater:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# KNX
knx:
 light: !include integrations/knx/light.yaml
 cover: !include integrations/knx/cover.yaml
 binary_sensor: !include integrations/knx/binary_sensor.yaml
 weather: !include integrations/knx/weather.yaml
 climate: !include integrations/knx/climate.yaml
 sensor: !include integrations/knx/sensor.yaml
 switch: !include integrations/knx/switch.yaml


# Enables a map showing the location of tracked devices
map:

#logger:
  #default: info
  #  logs:
  #  xknx: debug

# Delete historic data after 365 days
recorder:
  db_url: !env_var DB_CONNECTION
  purge_keep_days: 1500

# Track the sun
sun:


mobile_app:

mqtt:
  broker: 192.168.0.203
  port: 1883
  client_id: 'Homeassistant'
  username: svc_user
  password: !secret mqtt_password

weather:
- platform: darksky
  api_key: !secret dark_sky_api_password
  name: !secret home_name
  mode: daily

notify:
  # todo: replace with android app
- platform: pushbullet
  name: pushbullet_mwi
  api_key: !secret pushbullet_api

- platform: pushbullet
  name: pushbullet_kalo
  api_key: !secret kalo_pushbullet_api

- platform: group
  name: notifiers
  services:
      - service: pushbullet_mwi
      - service: pushbullet_kalo

wake_on_lan:
webostv:
    host: !secret living_room_tv
    name: livingroom_tv
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "A8:23:FE:5B:FD:F1"

spotify:
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_secret_id

media_player: !include media_player.yaml


switch: !include switch.yaml
camera: !include camera.yml
sensor: !include sensor.yaml
cover: !include cover.yaml
light: !include light.yaml
group: !include groups.yaml
vacuum: !include vacuum.yml
zone: !include zones.yaml
automation: !include_dir_list automations/
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
