---
# Weather
- platform: darksky
  api_key: !secret dark_sky_api_password
  language: 'de'
  forecast:
    - 0
  monitored_conditions:
    - summary
    - temperature
    - hourly_summary
    - temperature_high
    - wind_speed
    - humidity
    - pressure
    - temperature_low
    - precip_intensity
    - icon

# HA stats
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: disk_use_percent
      arg: /

- platform: mqtt
  name: garage_door_time_in_state
  state_topic: 'garadget/garage/status'
  value_template: '{{ value_json.time }}'

- platform: template
  sensors:
    garage_door_status:
      friendly_name: 'Torstatus'
      value_template: '{{ states.cover.garage.state }}'
      icon_template: '{% if is_state("cover.garage", "closed") %}mdi:garage{% else %}mdi:garage-open{% endif %}'
    next_trash:
      friendly_name: 'KNX Nächste Müllleerung Fixed length 14'
      value_template: '{{ states("sensor.trash_appointment")[0:14] }}'
    trash_appointment:
      friendly_name: 'Nächste Müllleerung'
      value_template: >
        {% set trash_date = as_datetime(strptime(state_attr("calendar.marvin_fam_wichmann_de", "start_time"), "%Y-%m-%d %H:%M:%S")).strftime("%d.%m") %}
        {% set trash = state_attr("calendar.marvin_fam_wichmann_de", "message") | replace("Kämpfelbach: ", "") %}
        {{ trash + " - " +  trash_date }}
    trash_appointment_days:
      friendly_name: 'Tage bis zur nächsten Müllleerung'
      value_template: >
        {% set trash_date = as_local(as_datetime(strptime(state_attr("calendar.marvin_fam_wichmann_de", "start_time"), "%Y-%m-%d %H:%M:%S"))) %}
        {{ (trash_date - as_local(utcnow())).days | int }}
