- platform: mqtt
  name: "rockrobo"
  supported_features:
    - pause
    - stop
    - start
    - return_home
    - battery
    - status
    - locate
    - clean_spot
    - fan_speed
    - send_command
  schema: state
  command_topic: "valetudo/rockrobo/command"
  state_topic: "valetudo/rockrobo/state"
  set_fan_speed_topic: "valetudo/rockrobo/set_fan_speed"
  fan_speed_list:
    - low
    - medium
    - high
    - max
    - mop
  send_command_topic: "valetudo/rockrobo/custom_command"
  json_attributes_topic: "valetudo/rockrobo/attributes"
  availability_topic: "valetudo/rockrobo/status"
