---
alias: 'Open sun protection blind in the abstellzimmer in the evening if enabled'
initial_state: True
trigger:
  platform: sun
  event: sunset
  offset: "+00:30"
condition:
  - condition: state
    entity_id: 'input_boolean.sun_protection'
    state: 'on'
action:
  - service: cover.open_cover
    entity_id: cover.sonne_abstellkammer
