---
alias: 'Trigger alexa notification to ask if she should open the door.'

id: 40844172-02cd-463e-aada-99a297d8a7d0
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.door_ring
    to: 'on'
action:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: 'Es klingelt. Soll ich die Tür öffnen?'
      event_id: 'actionable_notification_open_door'
      alexa_device: 'media_player.alexa_kueche'
