---
alias: 'Trigger alexa notification to ask if the blinds should be closed.'
initial_state: True
id: 1ea50f08-d85f-4cc5-8a4e-1cb728e81b13
trigger:
  - platform: template
    value_template: "{% if states.media_player.livingroom_tv.state | string == 'on' %}true{% endif %}"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'sun.sun'
      state: 'above_horizon'
    - condition: numeric_state
      entity_id: sensor.home_brightness_south
      above: 14000.00
action:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: 'Dein Fernseher ist jetzt an. Möchtest du dass ich die Rolläden im Wohnzimmer teilweiße schließe?'
      event_id: 'actionable_notification_close_covers_tv'
      alexa_device: 'media_player.alexa_kueche'
