---
alias: 'Close covers in the evening via actionable notification'
initial_state: True
id: 81973005-84e9-44e0-95b6-cdcafb904d6f
trigger:
  platform: event
  event_type: alexa_actionable_notification
  event_data:
    event_id: actionable_notification_close_covers_evening
    event_response_type: ResponseYes
action:
- service: cover.close_cover
  data:
    entity_id: cover.wohnen_esszimmer
- service: cover.close_cover
  data:
    entity_id: cover.kueche
- service: cover.close_cover
  data:
    entity_id: cover.wohnen_tv
- service: cover.close_cover
  data:
    entity_id: cover.wohnen_balkon
- service: cover.close_cover
  data:
    entity_id: cover.gast
- service: light.turn_on
  data:
    entity_id: light.wohnzimmer_sternenhimmel
- service: notify.alexa_media
  data_template:
    target: "media_player.alexa_kueche"
    message: "Deine Rolläden sind jetzt geschlossen."
    data:
      type: "tts"
