---
alias: 'Trigger alexa notification to ask if the blinds should be closed in the evening.'

id: 30844172-02cd-463e-aada-99a297d8a7d0
initial_state: True
trigger:
  - platform: numeric_state
    entity_id: sensor.home_brightness_south
    below: 50
action:
  - service: script.activate_alexa_actionable_notification
    data_template:
      text: 'Es wird langsam dunkel. Soll ich deine Rolläden für dich schließen und das Licht anschalten?'
      event_id: 'actionable_notification_close_covers_evening'
      alexa_device: 'media_player.alexa_kueche'
