---
alias: 'Binary sensor test counter=1 on'
id: d74e95dc-9b20-46cc-9c11-c32c76896511
trigger:
  platform: numeric_state
  entity_id: binary_sensor.cover_abstell
  attribute: counter
  above: 0
  below: 2
condition:
  - condition: state
    entity_id: binary_sensor.cover_abstell
    state: 'on'
action:
  - service: cover.open_cover
    entity_id: cover.sonne_abstellkammer
