---
alias: 'Take daily reminder'
initial_state: True
id: ca967e2a-b3e3-4b61-a72b-8d2193a5e1f6
trigger:
  - platform: time
    at: '18:00:00'
action:
  service: notify.pushbullet_mwi
  data_template:
    title: "Tablette nehmen"
    message: "Tablette nehmen!"
