---
alias: 'Get notified when garage door closes - automatic interaction from HA - intermediate closing state'
trigger:
  platform: state
  entity_id: cover.garage
  from: "closing"
  to: "closed"
action:
  - service: notify.notifiers
    data:
      title: Info
      message: Deine Garage ist jetzt geschlossen
