---
alias: 'Activate cabinet light in the hallway if motion is detected'
initial_state: True
trigger:
  platform: state
  entity_id: switch.flur_bewegung
  to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'off'
  - condition: state
    entity_id: media_player.livingroom_tv
    state: 'off'
action:
  - service: light.turn_on
    entity_id: light.flur
    data:
      brightness: 100
  - delay:
      minutes: 5
  - service: switch.turn_off
    entity_id:
      - switch.flur_bewegung
  - service: light.turn_off
    entity_id:
      - light.flur
