---
alias: 'Read NFC: Toggle garage state - KAL'
initial_state: True
id: 915e4cc8-e26c-42fb-b1f0-72be378ecd7d
trigger:
  platform: event
  event_type: tag_scanned
  event_data:
    device_id: 40c2d6dd5898874e
    tag_id: 471abf8c-f692-4c59-8b83-a850bdd57188
action:
  - service: cover.toggle
    entity_id: cover.garage
