---
alias: 'Activates night mode'
initial_state: True
id: c79eab0d-20ca-416b-8183-e866daef6f67
trigger:
  platform: state
  entity_id: input_boolean.night_mode
  to: 'on'
  for:
    seconds: 62
action:
  - service: switch.turn_on
    entity_id:
      - switch.schlafzimmer_steckdose_marvin
      - switch.schlafzimmer_wand_strom
