---
alias: 'Binary sensor test counter=1 on'
id: 9c66e778-d1bc-43fb-bd05-041c83106248
trigger:
  platform: numeric_state
  entity_id: binary_sensor.cover_abstell
  attribute: counter
  above: 0
  below: 2
condition:
  - condition: state
    entity_id: binary_sensor.cover_abstell
    state: 'off'
action:
  - service: cover.close_cover
    entity_id: cover.sonne_abstellkammer
