---
alias: 'Reset night mode'
id: b9de77aa-3660-4c00-85ff-543484ffc9a5
trigger:
  platform: sun
  event: sunrise
  offset: '+00:45'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.night_mode
  - service: switch.turn_off
    entity_id:
      - switch.schlafzimmer_steckdose_marvin
      - switch.schlafzimmer_wand_strom
