---
alias: 'Turns power plugs when main power is off - mainly used for the dashboard'
initial_state: True
id: e0f717a2-ea6e-42d8-9814-5300f6170ffe
trigger:
  platform: state
  entity_id: switch.schlafzimmer_wand_strom
  from: 'on'
  to: 'off'
action:
  - service: switch.turn_off
    entity_id:
      - switch.schlafzimmer_steckdose_marvin
