---
alias: 'Schlafzimmer RGB ON'
id: 920de72a-9911-4530-bcdf-9048f7f00cd7
trigger:
  platform: numeric_state
  entity_id: binary_sensor.schlafzimmer_rgb
  attribute: counter
  above: 0
  below: 2
condition:
  - condition: state
    entity_id: binary_sensor.schlafzimmer_rgb
    state: 'on'
action:
  - service: light.turn_on
    entity_id: light.schlafzimmer_strip
