---
name: Home Assistant CI

on:
  push:
  pull_request:

jobs:
  pre-commit:
    name: Pre Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v2.3.3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.1.2
        with:
          python-version: 3.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pre-commit
          pip list
          pre-commit --version
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  home_assistant_stable:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2.3.3
      - name: Copy stub files into configuration folder
        run: |
          cp .stubs/secrets.yaml secrets.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config . --script check_config --info all
        env:
          DB_CONNECTION: "user:pw@192.168.0.1/db"
  home_assistant_beta:
      needs: pre-commit
      runs-on: ubuntu-latest
      steps:
        - name: Getting your configuration from GitHub
          uses: actions/checkout@v2.3.3
        - name: Copy stub files into configuration folder
          run: |
            cp .stubs/secrets.yaml secrets.yaml
        - name: Home Assistant Version
          uses: "docker://homeassistant/home-assistant:beta"
          with:
            args: |
              python -m homeassistant --version
        - name: Home Assistant Check
          uses: "docker://homeassistant/home-assistant:beta"
          with:
            args: python -m homeassistant --config ./ --script check_config --info all
          env:
            DB_CONNECTION: "user:pw@192.168.0.1/db"
